from pathlib import Path
from dotenv import load_dotenv
import os

# Load .env if present
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = BASE_DIR / '.env'
if ENV_PATH.exists():
    load_dotenv(ENV_PATH)

# Reuse existing frontend data generated by process_all_data.py
FRONTEND_DATA_DIR = BASE_DIR.parent / 'frontend' / 'public' / 'data'
FAQS_PATH = FRONTEND_DATA_DIR / 'faqs.json'
EMBEDDINGS_PATH = FRONTEND_DATA_DIR / 'embeddings.json'

# RAG settings
MAX_CONTEXT_FAQS = 3
MIN_SIMILARITY_WEAK = 0.2
MIN_SIMILARITY_STRONG = 0.5

# LLM settings (OpenRouter)
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
OPENROUTER_API_BASE = os.getenv('OPENROUTER_API_BASE', 'https://openrouter.ai/api/v1')
OPENROUTER_MODEL = os.getenv('OPENROUTER_MODEL', 'meta-llama/llama-3.3-70b-instruct:free')
